CREATE SEQUENCE ADVISORY_PK_ADVISORY_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE ADVISORY
(
  PK_ADVISORY BIGINT NOT NULL DEFAULT NEXTVAL('ADVISORY_PK_ADVISORY_SEQ'::REGCLASS),
  FK_TUTOR BIGINT NOT NULL REFERENCES TUTOR(PK_TUTOR),
  QUESTION TEXT,
  ANSWER TEXT,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  STATUS INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT PK_ADVISORY PRIMARY KEY (PK_ADVISORY)
)
WITH (
  OIDS=FALSE
);