CREATE TABLE APP_USER_ROLE
(
  FK_APP_USER bigint NOT NULL,
  FK_APP_ROLE bigint NOT NULL,
  CONSTRAINT AUR_FK_APP_ROLE_AR_PK_APP_ROLE FOREIGN KEY (FK_APP_USER)
      REFERENCES APP_ROLE (PK_APP_ROLE) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT AUR_FK_APP_USER_AU_PK_APP_USER FOREIGN KEY (FK_APP_ROLE)
      REFERENCES APP_USER (PK_APP_USER) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);