CREATE SEQUENCE APP_ROLE_PK_APP_ROLE_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE APP_ROLE
(
  PK_APP_ROLE BIGINT NOT NULL DEFAULT NEXTVAL('APP_ROLE_PK_APP_ROLE_SEQ'::REGCLASS),
  CODE CHARACTER VARYING(10) NOT NULL,
  NAME CHARACTER VARYING(200) NOT NULL,
  USER_TYPE INTEGER,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_APP_ROLE PRIMARY KEY (PK_APP_ROLE),
  CONSTRAINT APP_ROLE_UNIQUE_CODE UNIQUE (CODE)
)
WITH (
  OIDS=FALSE
);
