CREATE SEQUENCE APP_USER_ACTIVITY_PK_APP_USER_ACTIVITY_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
  
CREATE TABLE APP_USER_ACTIVITY
(
  PK_APP_USER_ACTIVITY bigint NOT NULL DEFAULT nextval('APP_USER_ACTIVITY_PK_APP_USER_ACTIVITY_SEQ'::regclass),
  FK_APP_USER bigint NOT NULL,
  activity_name character varying(200) NOT NULL,
  created_by character varying(200) NOT NULL,
  creation_time timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT PK_APP_USER_ACTIVITY PRIMARY KEY (PK_APP_USER_ACTIVITY),
  CONSTRAINT AUA_FK_APP_USER_AU_PK_APP_USER FOREIGN KEY (FK_APP_USER)
      REFERENCES APP_USER (PK_APP_USER) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);

