CREATE SEQUENCE APP_USER_PASS_HIST_PK_APP_USER_PASS_HIST_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
  
CREATE TABLE APP_USER_PASS_HIST
(
  PK_APP_USER_PASS_HIST bigint NOT NULL DEFAULT nextval('APP_USER_PASS_HIST_PK_APP_USER_PASS_HIST_SEQ'::regclass),
  FK_APP_USER bigint NOT NULL,
  PASS_VALUE character varying(255) NOT NULL,
  CREATION_TIME timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT PK_APP_USER_PASS_HIST PRIMARY KEY (PK_APP_USER_PASS_HIST),
  CONSTRAINT AUPH_FK_APP_USER_AU_PK_APP_USER FOREIGN KEY (FK_APP_USER)
      REFERENCES APP_USER (PK_APP_USER) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);