CREATE SEQUENCE APP_PARAMETER_PK_APP_PARAMETER_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE APP_PARAMETER
(
  PK_APP_PARAMETER BIGINT NOT NULL DEFAULT NEXTVAL('APP_PARAMETER_PK_APP_PARAMETER_SEQ'::regclass),
  NAME CHARACTER VARYING(200) NOT NULL,
  VALUE CHARACTER VARYING(200) NOT NULL,
  DESCR TEXT,
  IS_VIEWABLE BOOLEAN,
  DATATYPE INTEGER,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_APP_PARAMETER PRIMARY KEY (PK_APP_PARAMETER)
)
WITH (
  OIDS=FALSE
);