CREATE SEQUENCE CONTACT_PK_CONTACT_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE CONTACT
(
  PK_CONTACT BIGINT NOT NULL DEFAULT NEXTVAL('CONTACT_PK_CONTACT_SEQ'::REGCLASS),
  FK_LOOKUP_CATEGORY_HELP BIGINT REFERENCES LOOKUP(PK_LOOKUP),
  FK_LOOKUP_CONTACT_TEMA BIGINT REFERENCES LOOKUP(PK_LOOKUP),
  NAME CHARACTER VARYING(100),
  TELP CHARACTER VARYING(20),
  EMAIL CHARACTER VARYING(100),
  ADDRESS TEXT,
  INSTANSI CHARACTER VARYING(100),
  MESSAGE TEXT,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_CONTACT PRIMARY KEY (PK_CONTACT)
)
WITH (
  OIDS=FALSE
);