CREATE SEQUENCE COURSE_PK_COURSE_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE COURSE
(
  PK_COURSE BIGINT NOT NULL DEFAULT NEXTVAL('COURSE_PK_COURSE_SEQ'::REGCLASS),
  FK_GROUP_COURSE BIGINT NOT NULL REFERENCES GROUP_COURSE(PK_GROUP_COURSE),
  CODE CHARACTER VARYING(100) NOT NULL,
  NAME CHARACTER VARYING(100),
  FK_LOOKUP_COURSE_CATEGORY BIGINT NOT NULL REFERENCES LOOKUP(PK_LOOKUP),
  SUBTITLE CHARACTER VARYING(100),
  BASIC_PICTURE_URL TEXT,
  FULL_DESCRIPTION TEXT,
  ADMISSION_REQUIREMENT TEXT,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  STATUS INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT PK_COURSE PRIMARY KEY (PK_COURSE)
)
WITH (
  OIDS=FALSE
);