CREATE SEQUENCE EVENT_PK_EVENT_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE EVENT
(
  PK_EVENT BIGINT NOT NULL DEFAULT NEXTVAL('EVENT_PK_EVENT_SEQ'::REGCLASS),
  CODE CHARACTER VARYING(100) NOT NULL,
  NAME CHARACTER VARYING(100),
  DESCRIPTION TEXT,
  EVENT_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  STATUS INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT PK_EVENT PRIMARY KEY (PK_EVENT)
)
WITH (
  OIDS=FALSE
);