ALTER TABLE EVENT DROP COLUMN CODE;
ALTER TABLE EVENT RENAME NAME TO TITLE;
ALTER TABLE EVENT ADD FK_LOOKUP_EVENT_STATUS BIGINT;
ALTER TABLE EVENT ADD EXCERPT TEXT;
ALTER TABLE EVENT ADD COVER_IMAGE_URL TEXT;