CREATE SEQUENCE GC_BASIC_INFO_PK_GC_BASIC_INFO_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE GC_BASIC_INFO
(
  PK_GC_BASIC_INFO BIGINT NOT NULL DEFAULT NEXTVAL('GC_BASIC_INFO_PK_GC_BASIC_INFO_SEQ'::REGCLASS),
  FK_GROUP_COURSE BIGINT REFERENCES GROUP_COURSE (PK_GROUP_COURSE),
  FK_LOOKUP_FIELD BIGINT REFERENCES LOOKUP(PK_LOOKUP),
  ORDER_NO INT,
  VALUE TEXT,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_GC_BASIC_INFO PRIMARY KEY (PK_GC_BASIC_INFO)
)
WITH (
  OIDS=FALSE
);