CREATE TABLE LOOKUP_GROUP
(
  LOOKUP_GROUP CHARACTER VARYING(100) NOT NULL,
  GROUP_DESCR CHARACTER VARYING(100) NOT NULL,
  IS_UPDATEABLE BOOLEAN,
  IS_VIEWABLE BOOLEAN
)
WITH (
  OIDS=FALSE
);