ALTER TABLE NEWS DROP COLUMN CODE;
ALTER TABLE NEWS RENAME NAME TO TITLE;
ALTER TABLE NEWS ADD FK_LOOKUP_NEWS_STATUS BIGINT;
ALTER TABLE NEWS ADD PUBLISH_DATE TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE NEWS ADD EXCERPT TEXT;