CREATE SEQUENCE PARTY_CONTACT_PK_PARTY_CONTACT_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE PARTY_CONTACT
(
  PK_PARTY_CONTACT BIGINT NOT NULL DEFAULT nextval('PARTY_CONTACT_PK_PARTY_CONTACT_SEQ'::regclass),
  FK_PARTY BIGINT NOT NULL,
  FK_LOOKUP_CONTACT_TYPE BIGINT,
  CONTACT CHARACTER VARYING(100) NOT NULL,
  CONSTRAINT PK_PARTY_CONTACT PRIMARY KEY (PK_PARTY_CONTACT),
  CONSTRAINT PC_FK_LOOKUP_CONTACT_TYPE_L_PK_LOOKUP FOREIGN KEY (FK_LOOKUP_CONTACT_TYPE)
      REFERENCES LOOKUP (PK_LOOKUP) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT PC_FK_PARTY_P_PK_PARTY FOREIGN KEY (FK_PARTY)
      REFERENCES PARTY (PK_PARTY) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);