CREATE SEQUENCE PARTY_ADDRESS_PK_PARTY_ADDRESS_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
  
CREATE TABLE PARTY_ADDRESS
(
  PK_PARTY_ADDRESS bigint NOT NULL DEFAULT nextval('PARTY_ADDRESS_PK_PARTY_ADDRESS_SEQ'::regclass),
  FK_PARTY bigint NOT NULL,
  FK_LOOKUP_ADDRESS_TYPE BIGINT,
  ALAMAT CHARACTER VARYING(255),
  FK_LOOKUP_ADDR_KELURAHAN BIGINT,
  FK_LOOKUP_ADDR_KECAMATAN BIGINT,
  FK_LOOKUP_ADDR_KABUPATEN_KOTA BIGINT,
  FK_LOOKUP_ADDR_PROVINSI BIGINT,
  KODEPOS INTEGER,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200),
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE,
  CONSTRAINT PK_PARTY_ADDRESS PRIMARY KEY (PK_PARTY_ADDRESS),
  CONSTRAINT PA_FK_LOOKUP_ADDR_KABUPATEN_KOTA_LA_PK_LOOKUP_ADDR FOREIGN KEY (FK_LOOKUP_ADDR_KABUPATEN_KOTA)
      REFERENCES LOOKUP_ADDRESS (PK_LOOKUP_ADDRESS) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT PA_FK_LOOKUP_ADDR_KECAMATAN_LA_PK_LOOKUP_ADDR FOREIGN KEY (FK_LOOKUP_ADDR_KECAMATAN)
      REFERENCES LOOKUP_ADDRESS (PK_LOOKUP_ADDRESS) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT PA_FK_LOOKUP_ADDR_KELURAHAN_LA_PK_LOOKUP_ADDR FOREIGN KEY (FK_LOOKUP_ADDR_KELURAHAN)
      REFERENCES LOOKUP_ADDRESS (PK_LOOKUP_ADDRESS) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT PA_FK_LOOKUP_ADDR_PROVINSI_LA_PK_LOOKUP_ADDR FOREIGN KEY (FK_LOOKUP_ADDR_PROVINSI)
      REFERENCES LOOKUP_ADDRESS (PK_LOOKUP_ADDRESS) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT PA_FK_LOOKUP_ADDRESS_TYPE_L_PK_LOOKUP FOREIGN KEY (FK_LOOKUP_ADDRESS_TYPE)
      REFERENCES LOOKUP (PK_LOOKUP) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT PA_FK_PARTY_P_PK_PARTY FOREIGN KEY (FK_PARTY)
      REFERENCES PARTY (PK_PARTY) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
