ALTER TABLE RESEARCH RENAME BASIC_PICTURE_URL TO IMAGE_URL;
ALTER TABLE RESEARCH RENAME NAME TO TITLE;
ALTER TABLE RESEARCH DROP COLUMN CODE;
ALTER TABLE RESEARCH RENAME FULL_DESCRIPTION TO ABSTRACT;
ALTER TABLE RESEARCH ADD COLUMN INTRODUCTION TEXT;
ALTER TABLE RESEARCH ADD COLUMN LITERATURE_REVIEW TEXT;
ALTER TABLE RESEARCH ADD COLUMN METHODS TEXT;
ALTER TABLE RESEARCH ADD COLUMN RESULTS TEXT;
ALTER TABLE RESEARCH RENAME ABSTRACT TO ABSTRACT_DESC;
ALTER TABLE RESEARCH DROP COLUMN FILE_URL;
ALTER TABLE RESEARCH DROP COLUMN FK_RESEARCH_TOPIC;
ALTER TABLE RESEARCH DROP COLUMN RESEARCH_DATE;
ALTER TABLE RESEARCH ADD COLUMN RESEARCH_DATE_FROM timestamp with time zone;
ALTER TABLE RESEARCH ADD COLUMN RESEARCH_DATE_TO timestamp with time zone;

ALTER TABLE RESEARCH DROP COLUMN created_by;
ALTER TABLE RESEARCH DROP COLUMN creation_time; 
ALTER TABLE RESEARCH DROP COLUMN modified_by;
ALTER TABLE RESEARCH DROP COLUMN modification_time; 
ALTER TABLE RESEARCH DROP COLUMN status;

ALTER TABLE RESEARCH ADD COLUMN status integer NOT NULL DEFAULT 1;
ALTER TABLE RESEARCH ADD COLUMN created_by character varying(200) NOT NULL;
ALTER TABLE RESEARCH ADD COLUMN creation_time timestamp with time zone NOT NULL DEFAULT now();
ALTER TABLE RESEARCH ADD COLUMN modified_by character varying(200) NOT NULL;
ALTER TABLE RESEARCH ADD COLUMN modification_time timestamp with time zone NOT NULL DEFAULT now();