CREATE SEQUENCE RESEARCH_RS_TOPIC_PK_RESEARCH_RESEARCH_TOPIC_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE RESEARCH_RESEARCH_TOPIC
(
  PK_RESEARCH_RESEARCH_TOPIC BIGINT NOT NULL DEFAULT NEXTVAL('RESEARCH_RS_TOPIC_PK_RESEARCH_RESEARCH_TOPIC_SEQ'::REGCLASS),
  FK_RESEARCH BIGINT NOT NULL REFERENCES RESEARCH(PK_RESEARCH),
  FK_RESEARCH_TOPIC BIGINT NOT NULL REFERENCES RESEARCH_TOPIC(PK_RESEARCH_TOPIC),
  CONSTRAINT PK_RESEARCH_RESEARCH_TOPIC PRIMARY KEY (PK_RESEARCH_RESEARCH_TOPIC)
)
WITH (
  OIDS=FALSE
);

CREATE SEQUENCE RESEARCH_RESEARCHER_PK_RESEARCH_RESEARCHER_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE RESEARCH_RESEARCHER
(
  PK_RESEARCH_RESEARCHER BIGINT NOT NULL DEFAULT NEXTVAL('RESEARCH_RESEARCHER_PK_RESEARCH_RESEARCHER_SEQ'::REGCLASS),
  FK_RESEARCH BIGINT NOT NULL REFERENCES RESEARCH(PK_RESEARCH),
  FK_PARTY BIGINT NOT NULL REFERENCES PARTY(PK_PARTY),
  CONSTRAINT PK_RESEARCH_RESEARCHER PRIMARY KEY (PK_RESEARCH_RESEARCHER)
)
WITH (
  OIDS=FALSE
);

CREATE SEQUENCE RESEARCH_TM_PLAN_PK_RESEARCH_TIME_PLANNING_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE RESEARCH_TIME_PLANNING
(
  PK_RESEARCH_TIME_PLANNING BIGINT NOT NULL DEFAULT NEXTVAL('RESEARCH_TM_PLAN_PK_RESEARCH_TIME_PLANNING_SEQ'::REGCLASS),
  FK_RESEARCH BIGINT NOT NULL REFERENCES RESEARCH(PK_RESEARCH),
  DATE_FROM timestamp with time zone,
  DATE_TO timestamp with time zone,
  TIME_FROM time,
  TIME_TO time,
  TITLE character varying(200),
  CONTENT TEXT,
  STATUS integer NOT NULL DEFAULT 1,
  CONSTRAINT PK_RESEARCH_TIME_PLANNING PRIMARY KEY (PK_RESEARCH_TIME_PLANNING)
)
WITH (
  OIDS=FALSE
);

CREATE SEQUENCE RESEARCH_BUDGETING_PK_RESEARCH_BUDGETING_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE RESEARCH_BUDGETING
(
  PK_RESEARCH_BUDGETING BIGINT NOT NULL DEFAULT NEXTVAL('RESEARCH_BUDGETING_PK_RESEARCH_BUDGETING_SEQ'::REGCLASS),
  FK_RESEARCH BIGINT NOT NULL REFERENCES RESEARCH(PK_RESEARCH),
  TITLE character varying(200),
  BUDGET_DATE timestamp with time zone,
  CONTENT TEXT,
  SIGN integer NOT NULL DEFAULT 1,
  AMOUNT numeric(24,4),
  STATUS integer NOT NULL DEFAULT 1,
  CONSTRAINT PK_RESEARCH_BUDGETING PRIMARY KEY (PK_RESEARCH_BUDGETING)
)
WITH (
  OIDS=FALSE
);

CREATE SEQUENCE RESEARCH_GOAL_TARGET_PK_RESEARCH_GOAL_TARGET_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE RESEARCH_GOAL_TARGET
(
  PK_RESEARCH_GOAL_TARGET BIGINT NOT NULL DEFAULT NEXTVAL('RESEARCH_GOAL_TARGET_PK_RESEARCH_GOAL_TARGET_SEQ'::REGCLASS),
  FK_RESEARCH BIGINT NOT NULL REFERENCES RESEARCH(PK_RESEARCH),
  TITLE character varying(200),
  CONTENT TEXT,
  FK_RESEARCH_TIME_PLANNING BIGINT REFERENCES RESEARCH_TIME_PLANNING(PK_RESEARCH_TIME_PLANNING),
  PROGRESS_TYPE integer NOT NULL DEFAULT 1,
  TARGET_DATE timestamp with time zone,
  STATUS integer NOT NULL DEFAULT 1,
  CONSTRAINT PK_RESEARCH_GOAL_TARGET PRIMARY KEY (PK_RESEARCH_GOAL_TARGET)
)
WITH (
  OIDS=FALSE
);

CREATE SEQUENCE RESEARCH_MEMO_PK_RESEARCH_MEMO_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE RESEARCH_MEMO
(
  PK_RESEARCH_MEMO BIGINT NOT NULL DEFAULT NEXTVAL('RESEARCH_MEMO_PK_RESEARCH_MEMO_SEQ'::REGCLASS),
  FK_RESEARCH BIGINT NOT NULL REFERENCES RESEARCH(PK_RESEARCH),
  TITLE character varying(200),
  CONTENT TEXT,
  NOTIFY_ME_DATE timestamp with time zone,
  STATUS integer NOT NULL DEFAULT 1,
  CONSTRAINT PK_RESEARCH_MEMO PRIMARY KEY (PK_RESEARCH_MEMO)
)
WITH (
  OIDS=FALSE
);

CREATE SEQUENCE RESEARCH_FILE_PK_RESEARCH_FILE_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE RESEARCH_FILE
(
  PK_RESEARCH_FILE BIGINT NOT NULL DEFAULT NEXTVAL('RESEARCH_FILE_PK_RESEARCH_FILE_SEQ'::REGCLASS),
  FK_RESEARCH BIGINT NOT NULL REFERENCES RESEARCH(PK_RESEARCH),
  TITLE character varying(200),
  FILE TEXT,
  UPLOAD_DATE timestamp with time zone,
  STATUS integer NOT NULL DEFAULT 1,
  CONSTRAINT PK_RESEARCH_FILE PRIMARY KEY (PK_RESEARCH_FILE)
)
WITH (
  OIDS=FALSE
);