CREATE SEQUENCE RUNTIME_USER_LOGIN_USER_ID_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE RUNTIME_USER_LOGIN
(
  USER_ID BIGINT NOT NULL DEFAULT NEXTVAL('RUNTIME_USER_LOGIN_USER_ID_SEQ'::regclass),
  ACCESS_INFO TEXT NOT NULL,
  EMAIL CHARACTER VARYING(200) NOT NULL,
  USER_NAME CHARACTER VARYING(200) NOT NULL,
  NAME CHARACTER VARYING(200) NOT NULL,
  USER_TYPE INTEGER NOT NULL,
  SESSION_TYPE INTEGER NOT NULL,
  LOGIN_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  REMOTE_ADDRESS CHARACTER VARYING(45) NOT NULL,
  COMPANY_LIST TEXT,
  COMPANY_SELECTED BIGINT,
  CONSTRAINT USER_ID PRIMARY KEY (USER_ID)
)
WITH (
  OIDS=FALSE
);