CREATE SEQUENCE STUDENT_COURSE_PK_STUDENT_COURSE_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE STUDENT_COURSE
(
  PK_STUDENT_COURSE BIGINT NOT NULL DEFAULT NEXTVAL('STUDENT_COURSE_PK_STUDENT_COURSE_SEQ'::REGCLASS),
  FK_STUDENT BIGINT NOT NULL REFERENCES STUDENT(PK_STUDENT),
  FK_COURSE BIGINT NOT NULL REFERENCES COURSE(PK_COURSE),
  ENROLL_DATE TIMESTAMP WITH TIME ZONE,
  FK_LOOKUP_STUDENT_COURSE_STATUS BIGINT NOT NULL REFERENCES LOOKUP(PK_LOOKUP),
  LAST_ACTION_DATE TIMESTAMP WITH TIME ZONE,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  STATUS INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT PK_STUDENT_COURSE PRIMARY KEY (PK_STUDENT_COURSE)
)
WITH (
  OIDS=FALSE
);