CREATE SEQUENCE TUTOR_PK_TUTOR_SEQ
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;

CREATE TABLE TUTOR
(
  PK_TUTOR BIGINT NOT NULL DEFAULT NEXTVAL('TUTOR_PK_TUTOR_SEQ'::REGCLASS),
  NAME CHARACTER VARYING(100),
  PROFILE_DESCRIPTION TEXT,
  CREATED_BY CHARACTER VARYING(200) NOT NULL,
  CREATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  MODIFIED_BY CHARACTER VARYING(200) NOT NULL,
  MODIFICATION_TIME TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  STATUS INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT PK_TUTOR PRIMARY KEY (PK_TUTOR)
)
WITH (
  OIDS=FALSE
);