DROP VIEW VW_STUDENT_LIST;

CREATE OR REPLACE VIEW VW_STUDENT_LIST
AS
SELECT S.PK_STUDENT, 
	S.NAME,
	S.PHONE_NUMBER, 
	S.EMAIL, 
	LO.PK_LOOKUP AS FK_LOOKUP_STUDENT_STATUS, 
	LO.CODE AS STUDENT_STATUS_CODE, 
	LO.NAME AS STUDENT_STATUS_LOOKUP_NAME,
	CL.CURRENT_LEARNING AS CURRENT_LEARNING,
	CP.PASSED_LEARNING AS PASSED_LEARNING,
	SC.ENROLL_DATE AS ENROLL_DATE,
	S.STATUS AS STATUS
FROM STUDENT S
LEFT JOIN LOOKUP LO ON LO.PK_LOOKUP = S.FK_LOOKUP_STUDENT_STATUS
LEFT JOIN (
	SELECT SC.FK_STUDENT, ARRAY_TO_STRING(ARRAY_AGG(SC.FK_COURSE), ';') AS CURRENT_LEARNING FROM STUDENT_COURSE SC
	INNER JOIN LOOKUP L ON L.PK_LOOKUP = SC.FK_LOOKUP_STUDENT_COURSE_STATUS AND L.CODE = 'EN'
	GROUP BY SC.FK_STUDENT) CL ON CL.FK_STUDENT = S.PK_STUDENT
LEFT JOIN (
	SELECT SC.FK_STUDENT, ARRAY_TO_STRING(ARRAY_AGG(SC.FK_COURSE), ';') AS PASSED_LEARNING FROM STUDENT_COURSE SC
	INNER JOIN LOOKUP L ON L.PK_LOOKUP = SC.FK_LOOKUP_STUDENT_COURSE_STATUS AND L.CODE = 'PA'
	GROUP BY SC.FK_STUDENT) CP ON CP.FK_STUDENT = S.PK_STUDENT
LEFT JOIN STUDENT_COURSE SC ON SC.FK_STUDENT = S.PK_STUDENT;