CREATE OR REPLACE VIEW VW_STUDENT_LIST
AS
SELECT S.PK_STUDENT, 
	S.NAME,
	S.PHONE_NUMBER, 
	S.EMAIL, 
	LO.PK_LOOKUP AS FK_LOOKUP_STUDENT_STATUS, 
	LO.CODE AS STUDENT_STATUS_CODE, 
	LO.NAME AS STUDENT_STATUS_LOOKUP_NAME,
	S.STATUS AS STATUS 
FROM STUDENT S
LEFT JOIN LOOKUP LO ON LO.PK_LOOKUP = S.FK_LOOKUP_STUDENT_STATUS;