-- Dashboard Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (110, 100, 'Statistik Contact Us', 'INT_DB_STATISTIC_CONTACT_US', '#', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (120, 100, 'Research Management Update', 'INT_DB_RESEARCH_MANAGEMENT_UPDATE', '#', true, 1, 2);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (130, 100, 'Advisory Consulting Notification', 'INT_DB_ADVISORY_CONSULTING_NOTIF', '#', true, 1, 3);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (140, 100, 'Contact Us Notification', 'INT_DB_CONTACT_US_NOTIF', '#', true, 1, 4);

-- Front End Display Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (300, 1, 'Front End Display', 'INT_FRONT_END', '#', true, 1, 3);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (310, 300, 'Front End Menu', 'INT_FE_MENU', '#', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (320, 300, 'Slide Show', 'INT_FE_SLIDE_SHOW', '#', true, 1, 2);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (330, 300, 'Background Image', 'INT_FE_BACKGROUND_IMAGE', '#', true, 1, 3);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (340, 300, 'Footer', 'INT_FE_FOOTER', '#', true, 1, 4);

-- About Us Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (400, 1, 'About Us', 'INT_ABOUT_US', '#', true, 1, 4);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (410, 400, 'About Us', 'INT_AU_COMMON_POST', '/do/aboutUs/commonPost/showList', true, 1, 1);

-- Activity Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (500, 1, 'Activity', 'INT_ACTIVITY', '#', true, 1, 5);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (510, 500, 'Engagement', 'INT_ACT_ENGAGEMENT', '/do/aboutUs/engagement/showList', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (520, 500, 'Program', 'INT_ACT_PROGRAM', '/do/aboutUs/programPost/showList', true, 1, 2);

-- Publication Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (600, 1, 'Publication', 'INT_PUBLICATION', '#', true, 1, 6);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (610, 600, 'eBook', 'INT_PUB_EBOOK', '/do/publication/digitalBook/showList', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (620, 600, 'News', 'INT_PUB_NEWS', '/do/news/newsMaintenance/showList', true, 1, 2);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (630, 600, 'Event', 'INT_PUB_EVENT', '/do/event/eventMaintenance/showList', true, 1, 3);

-- Learning Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (700, 1, 'Learning', 'INT_LEARNING', '#', true, 1, 7);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (710, 700, 'Program', 'INT_LEARNING_PROGRAM', '#', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (720, 700, 'Course Tag', 'INT_LEARNING_COURSE_TAG', '/do/course/groupCourse/showList', true, 1, 2);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (730, 700, 'Course', 'INT_LEARNING_COURSE', '/do/course/course/showList', true, 1, 3);

-- Research Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (800, 1, 'Research', 'INT_RESEARCH', '#', true, 1, 8);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (810, 800, 'Topic', 'INT_RESEARCH_TOPIC', '/do/research/researchTopic/showList', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (820, 800, 'Maintenance', 'INT_RESEARCH_MAINTENANCE', '/do/research/researchMaintenance/showList', true, 1, 2);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (830, 800, 'Management', 'INT_RESEARCH_MANAGEMENT', '#', true, 1, 3);

-- Advisory Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (900, 1, 'Advisory', 'INT_ADVISORY', '#', true, 1, 9);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (910, 900, 'Sub Menu', 'INT_ADVISORY_SUB_MENU', '#', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (920, 900, 'Common Post', 'INT_ADVISORY_COMMON_POST', '#', true, 1, 2);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (930, 900, 'Issue and insights', 'INT_ADVISORY_ISSUE_INSIGHT', '#', true, 1, 3);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (940, 900, 'Consulting', 'INT_ADVISORY_CONSULTING', '#', true, 1, 4);

-- Student Database
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1000, 1, 'Student Database', 'INT_STUDENT_DATABASE', '#', true, 1, 10);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1010, 1000, 'Maintenance', 'INT_SD_MAINTENANCE', '/do/student/showList', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1020, 1000, 'Update Learning Status', 'INT_SD_UPDATE_LEARNING', '#', true, 1, 2);

-- Contact Us
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1100, 1, 'Contact Us', 'INT_CONTACT_US', '#', true, 1, 11);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1110, 1100, 'Contact Us', 'INT_CU_MAINTENANCE', '#', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1120, 1100, 'User Contact', 'INT_CU_USER_CONTACT', '#', true, 1, 2);