INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (1, null, 'Internal Function', 'INT_INTERNAL_FUNCTION', null, true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (100, 1, 'Dashboard', 'INT_DASHBOARD', '/do/dashboard', true, 1, 1);

INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (200, 1, 'Administrator', 'INT_ADMINISTRATOR', '#', true, 1, 2);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (210, 200, 'App Role', 'INT_APP_ROLE', '/do/appRoleMaintenance/showList', true, 1, 1);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (220, 200, 'App User', 'INT_APP_USER', '/do/userMaintenance/showList', true, 1, 2);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (230, 200, 'System Parameter', 'INT_SYSTEM_PARAMETER', '/do/systemParameter/showList', true, 1, 3);
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (240, 200, 'Reference', 'INT_REFERENCE', '/do/lookupGroup/showList', true, 1, 4);