DELETE FROM APP_ROLE_FUNCTION WHERE FK_APP_FUNCTION IN (
SELECT PK_APP_FUNCTION FROM APP_FUNCTION WHERE DESCR IN ('INT_DB_STATISTIC_CONTACT_US', 
'INT_DB_RESEARCH_MANAGEMENT_UPDATE', 'INT_DB_ADVISORY_CONSULTING_NOTIF', 'INT_DB_CONTACT_US_NOTIF');

COMMIT;