-- Learning Menu
INSERT INTO APP_FUNCTION (PK_APP_FUNCTION, FK_APP_FUNCTION_PARENT, NAME, DESCR, ACCESS_PAGE, IS_ACTIVE, USER_TYPE, ORDER_NO)
VALUES (740, 700, 'Course Tag', 'INT_LEARNING_COURSE_TAG', '/do/course/courseTag/showList', true, 1, 4);
UPDATE APP_FUNCTION SET NAME = 'Group Course', DESCR = 'INT_LEARNING_GROUP_COURSE'
WHERE PK_APP_FUNCTION = '720';


