INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('GENDER', 'MA', 'Male', 'Male', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('GENDER', 'FE', 'Female', 'Female', 2, 1, 'SYSTEM', 'SYSTEM');
COMMIT;

INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('STUDENT_STATUS', 'AC', 'Active', 'Active', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('STUDENT_STATUS', 'NA', 'Not Active', 'Not Active', 2, 1, 'SYSTEM', 'SYSTEM');
COMMIT;

INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('ENROLLMENT_STATUS', 'EN', 'Enrolled', 'Enrolled', 1, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('ENROLLMENT_STATUS', 'PA', 'Passed', 'Passed', 2, 1, 'SYSTEM', 'SYSTEM');
INSERT INTO LOOKUP (LOOKUP_GROUP, CODE, NAME, DESCR, ORDER_NO, STATUS, CREATED_BY, MODIFIED_BY) 
VALUES ('ENROLLMENT_STATUS', 'FA', 'Failed', 'Failed', 3, 1, 'SYSTEM', 'SYSTEM');
COMMIT;