package id.base.app.util.dao;

public enum Operator {
	EQUALS, EQUALS_IGNORE_CASE , GREATER_THAN , LESS_THAN , EQUALS_OR_GREATER_THAN , SQL_RESTRICTION ,
		EQUALS_OR_LESS_THAN  , NOT_EQUAL , LIKE  , IN , OR , AND , IS_NULL , IS_NOT_NULL, NOT_IN_ARRAY, IN_ARRAY, NOT_IN, SIMILAR_TO, LIKE_COLUMN
}
